-- ====================================================================
-- MENAKKHI SAREES - SUPABASE DATABASE SCHEMA & RLS SECURITY POLICIES
-- ====================================================================

-- 1. EXTENSIONS
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 2. TABLES DEFINITIONS

-- A. Categories Table
CREATE TABLE IF NOT EXISTS public.categories (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    name TEXT UNIQUE NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

-- B. Products Table
CREATE TABLE IF NOT EXISTS public.products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    price NUMERIC(10,2) NOT NULL CHECK (price >= 0),
    image_url TEXT NOT NULL,
    category TEXT NOT NULL,
    description TEXT NOT NULL DEFAULT '',
    in_stock BOOLEAN DEFAULT TRUE NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

-- C. User Profiles Table (Linked to auth.users - NEVER stores raw passwords)
CREATE TABLE IF NOT EXISTS public.profiles (
    id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    name TEXT,
    email TEXT,
    role TEXT DEFAULT 'customer' NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

-- D. Shopping Cart Items Table
CREATE TABLE IF NOT EXISTS public.cart_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
    product_id BIGINT REFERENCES public.products(id) ON DELETE CASCADE NOT NULL,
    quantity INTEGER DEFAULT 1 NOT NULL CHECK (quantity > 0),
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

-- E. Orders Table
CREATE TABLE IF NOT EXISTS public.orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
    total_amount NUMERIC(10,2) NOT NULL CHECK (total_amount >= 0),
    status TEXT DEFAULT 'Pending' NOT NULL,
    contact_number TEXT NOT NULL,
    shipping_address TEXT NOT NULL,
    shipping_destination JSONB NOT NULL DEFAULT '{}'::jsonb,
    payment_details JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

-- F. Order Line Items Table
CREATE TABLE IF NOT EXISTS public.order_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT REFERENCES public.orders(id) ON DELETE CASCADE NOT NULL,
    product_id BIGINT REFERENCES public.products(id) ON DELETE CASCADE NOT NULL,
    quantity INTEGER NOT NULL CHECK (quantity > 0),
    price_at_purchase NUMERIC(10,2) NOT NULL CHECK (price_at_purchase >= 0),
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

-- G. Product Comments & Reviews Table
CREATE TABLE IF NOT EXISTS public.product_comments (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    product_id BIGINT REFERENCES public.products(id) ON DELETE CASCADE NOT NULL,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
    user_email TEXT NOT NULL,
    rating INTEGER NOT NULL CHECK (rating >= 1 AND rating <= 5),
    comment TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

-- H. Newsletter Subscribers Table
CREATE TABLE IF NOT EXISTS public.subscribers (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    email TEXT UNIQUE NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);


-- 3. AUTOMATIC PROFILE CREATION TRIGGER ON SIGNUP
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.profiles (id, name, email)
  VALUES (
    NEW.id,
    COALESCE(NEW.raw_user_meta_data->>'display_name', NEW.raw_user_meta_data->>'full_name', SPLIT_PART(NEW.email, '@', 1)),
    NEW.email
  )
  ON CONFLICT (id) DO UPDATE
  SET name = EXCLUDED.name, email = EXCLUDED.email;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Drop trigger if exists and recreate
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();


-- 4. PUBLIC RPC FUNCTION: TOP SELLING PRODUCTS
CREATE OR REPLACE FUNCTION public.get_public_top_sales()
RETURNS TABLE (
    id BIGINT,
    title TEXT,
    image_url TEXT,
    price NUMERIC,
    sales_count BIGINT
) AS $$
BEGIN
    RETURN QUERY
    SELECT 
        p.id,
        p.title,
        p.image_url,
        p.price,
        COALESCE(SUM(oi.quantity), 0)::BIGINT AS sales_count
    FROM public.products p
    LEFT JOIN public.order_items oi ON oi.product_id = p.id
    GROUP BY p.id, p.title, p.image_url, p.price
    ORDER BY sales_count DESC, p.id DESC
    LIMIT 20;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;


-- 5. ROW LEVEL SECURITY (RLS) POLICIES
ALTER TABLE public.categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.cart_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.order_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.product_comments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.subscribers ENABLE ROW LEVEL SECURITY;

-- Categories RLS
DROP POLICY IF EXISTS "Public categories read" ON public.categories;
CREATE POLICY "Public categories read" ON public.categories FOR SELECT USING (true);
DROP POLICY IF EXISTS "Admin categories manage" ON public.categories;
CREATE POLICY "Admin categories manage" ON public.categories FOR ALL USING (auth.role() = 'authenticated');

-- Products RLS
DROP POLICY IF EXISTS "Public products read" ON public.products;
CREATE POLICY "Public products read" ON public.products FOR SELECT USING (true);
DROP POLICY IF EXISTS "Admin products manage" ON public.products;
CREATE POLICY "Admin products manage" ON public.products FOR ALL USING (auth.role() = 'authenticated');

-- Profiles RLS
DROP POLICY IF EXISTS "Users read own profile" ON public.profiles;
CREATE POLICY "Users read own profile" ON public.profiles FOR SELECT USING (auth.uid() = id OR auth.role() = 'authenticated');
DROP POLICY IF EXISTS "Users update own profile" ON public.profiles;
CREATE POLICY "Users update own profile" ON public.profiles FOR UPDATE USING (auth.uid() = id);

-- Cart Items RLS
DROP POLICY IF EXISTS "Users manage own cart" ON public.cart_items;
CREATE POLICY "Users manage own cart" ON public.cart_items FOR ALL USING (auth.uid() = user_id);

-- Orders RLS
DROP POLICY IF EXISTS "Users read own orders" ON public.orders;
CREATE POLICY "Users read own orders" ON public.orders FOR SELECT USING (auth.uid() = user_id OR auth.role() = 'authenticated');
DROP POLICY IF EXISTS "Users insert own orders" ON public.orders;
CREATE POLICY "Users insert own orders" ON public.orders FOR INSERT WITH CHECK (auth.uid() = user_id);
DROP POLICY IF EXISTS "Admin update orders" ON public.orders;
CREATE POLICY "Admin update orders" ON public.orders FOR UPDATE USING (auth.role() = 'authenticated');
DROP POLICY IF EXISTS "Admin delete orders" ON public.orders;
CREATE POLICY "Admin delete orders" ON public.orders FOR DELETE USING (auth.role() = 'authenticated');

-- Order Items RLS
DROP POLICY IF EXISTS "Users read own order items" ON public.order_items;
CREATE POLICY "Users read own order items" ON public.order_items FOR SELECT USING (
    EXISTS (SELECT 1 FROM public.orders WHERE orders.id = order_items.order_id AND (orders.user_id = auth.uid() OR auth.role() = 'authenticated'))
);
DROP POLICY IF EXISTS "Users insert own order items" ON public.order_items;
CREATE POLICY "Users insert own order items" ON public.order_items FOR INSERT WITH CHECK (
    EXISTS (SELECT 1 FROM public.orders WHERE orders.id = order_items.order_id AND orders.user_id = auth.uid())
);
DROP POLICY IF EXISTS "Admin delete order items" ON public.order_items;
CREATE POLICY "Admin delete order items" ON public.order_items FOR DELETE USING (auth.role() = 'authenticated');

-- Product Comments RLS
DROP POLICY IF EXISTS "Public comments read" ON public.product_comments;
CREATE POLICY "Public comments read" ON public.product_comments FOR SELECT USING (true);
DROP POLICY IF EXISTS "Authenticated comment creation" ON public.product_comments;
CREATE POLICY "Authenticated comment creation" ON public.product_comments FOR INSERT WITH CHECK (auth.uid() = user_id);

-- Subscribers RLS
DROP POLICY IF EXISTS "Public subscribe" ON public.subscribers;
CREATE POLICY "Public subscribe" ON public.subscribers FOR INSERT WITH CHECK (true);
DROP POLICY IF EXISTS "Read subscribers" ON public.subscribers;
CREATE POLICY "Read subscribers" ON public.subscribers FOR SELECT USING (true);
DROP POLICY IF EXISTS "Unsubscribe" ON public.subscribers;
CREATE POLICY "Unsubscribe" ON public.subscribers FOR DELETE USING (true);


-- 6. INITIAL SEED DATA FOR SAREE E-COMMERCE STORE
INSERT INTO public.categories (name) VALUES
('Katan'),
('Rajshahi Silk'),
('Jamdani'),
('Georgette'),
('Muslin'),
('Organza'),
('Bridal Collection'),
('Chiffon')
ON CONFLICT (name) DO NOTHING;

INSERT INTO public.products (title, price, image_url, category, description, in_stock) VALUES
('Royal Kanchipuram Pure Katan Silk Saree', 16500.00, 'https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=800&auto=format&fit=crop', 'Katan', 'Traditional handwoven pure Katan silk saree enriched with intricate gold zari weave borders and grand pallu. Perfect for weddings and festive grandeur.', true),
('Dhakai Muslin Handloom Jamdani Saree', 18500.00, 'https://images.unsplash.com/photo-1617627143750-d86bc21e42bb?w=800&auto=format&fit=crop', 'Jamdani', 'Authentic 80-count Dhakai Muslin Jamdani featuring delicate geometric motifs woven by artisan master weavers from Narayanganj.', true),
('Pure Rajshahi Mulberry Silk Saree', 9200.00, 'https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?w=800&auto=format&fit=crop', 'Rajshahi Silk', '100% natural Rajshahi Mulberry silk with subtle sheen, hand block printed contrast borders, and lightweight comfortable wear.', true),
('Embroidered Designer Pure Georgette Saree', 7800.00, 'https://images.unsplash.com/photo-1609357605129-26f69add5d6e?w=800&auto=format&fit=crop', 'Georgette', 'Flowing lightweight georgette saree featuring intricate Zardozi thread embroidery, glass cut beads, and matching unstitched blouse piece.', true),
('Traditional Heritage Imperial Muslin Saree', 24000.00, 'https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=800&auto=format&fit=crop', 'Muslin', 'Ultra-light heirloom hand-spun Muslin saree with fine metallic motif detailing. A masterpiece of traditional Bengali craft.', true),
('Floral Threadwork Sheer Organza Saree', 8500.00, 'https://images.unsplash.com/photo-1617627143750-d86bc21e42bb?w=800&auto=format&fit=crop', 'Organza', 'Contemporary sheer organza saree with delicate pastel floral embroidery along scallops and matching raw silk blouse piece.', true),
('Crimson Bridal Zardozi Silk Saree', 28500.00, 'https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?w=800&auto=format&fit=crop', 'Bridal Collection', 'Exclusive bridal silk saree in deep crimson red with heavy metallic hand zardozi work, stone embellishments, and grand royal border.', true),
('Pastel Chiffon Saree with Pearl Lace', 6500.00, 'https://images.unsplash.com/photo-1609357605129-26f69add5d6e?w=800&auto=format&fit=crop', 'Chiffon', 'Soft pastel ombre chiffon saree featuring delicate hand-sewn pearl trim lace along edges for an elegant evening look.', true)
ON CONFLICT DO NOTHING;
