import React, { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { supabase } from '../supabaseClient';
import Navbar from '../components/Navbar';
import Footer from '../components/Footer';
import { getErrorMessage } from '../utils/errorHandling';

export default function Login() {
  const navigate = useNavigate();
  const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [errorMsg, setErrorMsg] = useState<string | null>(null); const [loading, setLoading] = useState(false);
  const handleAuthSubmit = async (e: React.FormEvent) => { e.preventDefault(); setLoading(true); setErrorMsg(null); try { const { data, error } = await supabase.auth.signInWithPassword({ email: email.trim().toLowerCase(), password }); if (error) throw new Error(error.message.toLowerCase().includes('invalid login credentials') ? 'Incorrect email or password. Please check your credentials.' : error.message); if (data?.user) navigate('/'); } catch (err) { setErrorMsg(getErrorMessage(err)); } finally { setLoading(false); } };
  return <div className="min-h-screen flex flex-col bg-brand-secondary font-sans text-brand-ink"><Navbar /><main className="flex flex-1 items-center justify-center px-5 py-12"><div className="grid w-full max-w-5xl overflow-hidden border border-brand-line bg-white shadow-xl md:grid-cols-[.85fr_1.15fr]"><aside className="hidden bg-brand-primary p-10 text-brand-secondary md:flex md:flex-col md:justify-between"><div><p className="text-[10px] font-bold uppercase tracking-[.3em] text-brand-secondary/70">Meenakkhi / Member access</p><h2 className="mt-20 max-w-xs font-serif text-5xl leading-[1.05]">Return to your edit.</h2></div><p className="max-w-xs border-t border-brand-secondary/20 pt-5 text-sm leading-6 text-brand-secondary/70">Your saved sarees, order notes, and considered choices are waiting.</p></aside><section className="p-7 sm:p-12"><div className="mb-9"><p className="text-[10px] font-bold uppercase tracking-[.25em] text-brand-accent">Welcome back</p><h1 className="mt-3 font-serif text-4xl text-brand-primary-dark">Sign in</h1><p className="mt-2 text-sm leading-6 text-brand-primary/70">Access your collection and order history.</p></div>{errorMsg && <div className="mb-5 border border-brand-accent/40 bg-brand-accent/10 p-3 text-xs font-semibold text-brand-primary-dark">{errorMsg}</div>}<form onSubmit={handleAuthSubmit} className="space-y-5"><label className="block"><span className="mb-2 block text-[10px] font-bold uppercase tracking-[.18em] text-brand-primary">Email address</span><input type="email" required value={email} onChange={(e) => setEmail(e.target.value)} placeholder="name@example.com" className="w-full border-b border-brand-line bg-transparent px-0 py-3 text-sm outline-none transition placeholder:text-brand-primary/35 focus:border-brand-accent" /></label><label className="block"><span className="mb-2 block text-[10px] font-bold uppercase tracking-[.18em] text-brand-primary">Password</span><input type="password" required value={password} onChange={(e) => setPassword(e.target.value)} placeholder="Enter your password" className="w-full border-b border-brand-line bg-transparent px-0 py-3 text-sm outline-none transition placeholder:text-brand-primary/35 focus:border-brand-accent" /></label><button disabled={loading} className="mt-4 w-full bg-brand-primary-dark px-5 py-4 text-xs font-bold uppercase tracking-[.2em] text-brand-secondary transition hover:bg-brand-primary disabled:opacity-60">{loading ? 'Signing in...' : 'Sign in securely'}</button></form><p className="mt-8 text-center text-sm text-brand-primary/65">New to Meenakkhi? <button onClick={() => navigate('/register')} className="font-bold text-brand-accent underline underline-offset-4">Create an account</button></p></section></div></main><Footer /></div>;
}
